[tool.poetry]
name = "quizzler"
version = "0.1.0"
description = ""
authors = ["Jeff Do <jephdo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
jinja2 = "^3.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
